exports.fr = {
    title: "À propos",
    description: "Guillaume Pelletier-Auger est un artiste.",
    content: `<i>Guillaume</i> est une série d'images générées par une variété de fonctions itératives.
    Elles ont été créées avec p5.js.`
};

exports.en = {
    title: "About",
    description: "Guillaume Pelletier-Auger is an artist.",
    content: `<i>Guillaume</i> is a series of images generated by various iterated functions. 
    They were created in JavaScript with the p5.js library.`
}

exports.link = null;
