exports.fr = {
    title: "Les Dunes",
    description: "Une série d'image générées par des fonctions itératives.",
    content: `<i>Les Dunes</i> est une série d'images générées par une variété de fonctions itératives.
    Elles ont été créées avec p5.js.`
};

exports.en = {
    title: "Dunes",
    description: "A series of images generated by iterated functions.",
    content: `<i>Dunes</i> is a series of images generated by various iterated functions. 
    They were created in JavaScript with the p5.js library.`
}

exports.link = null;
