exports.page = {
    title_fr: "Les Dunes",
    title_en: "Dunes",
    content_fr: `<i>Les Dunes</i> est une série d'images générées par une variété de fonctions itératives.
    Elles ont été créées avec p5.js.
    `,
    content_en: `<i>Dunes</i> is a series of images generated by various iterated functions. They were created
    in JavaScript with the p5.js library.
    `,
};
