exports.fr = {
    title: "Les pavages de Truchet",
    date: "Hiver 2017 - En cours",
    description: "Pavages et mathématiques françaises du XVIIe siècle",
    content: String.raw `
    <div id="page">
    <div id="abstract"><div id="abstract-title">Résumé</div>
    Une exploration des pavages qui passe par mille différents
    chemins et qui se termine (pour l'instant) avec quelques images colorées 
    et une infinité d'avenues non explorées.</div>
    <img src="../../images/truchet/truchet001.jpg">
    <h3>Premiers pas vers les pavages ; le génie inspirant de Marjorie Rice</h3>
    <p>J'ai démarré ce projet avec un désir vif mais très flou : celui de réaliser 
    une animation abstraite pour accompagner un morceau musical d'Anna Meredith. 
    La musique de Meredith m'évoque de vagues images très colorées 
    et des mouvements agités et décisifs, mais par quels procédés ces images pourraient-elles être
    construites ? À quoi <i>ressemble</i> cette musique ?</p>

    <p>J'étais depuis un moment très curieux d'explorer les pavages, un domaine
    mathématique énorme et riche, et duquel je ne comprends presque rien. 
    En cherchant sur le Web, j'ai découvert par hasard l'histoire de Marjorie Rice.</p>

    <p>En 1972, Marjorie Rice était une femme au foyer qui aimait lire les chroniques
    mathématiques de Martin Gardner. Elle n'avait pas de formation post-secondaire
    en mathématiques mais s'intéressait beaucoup à ce domaine. Après avoir lu une chronique
    de Gardner sur les pavages, elle s'est mise à y travailler et a découvert de nouveaux pavages
    qui étaient restés introuvés des mathématiciens professionnels. De plus, sa méthode de travail
    était en elle-même aussi géniale que ses résultats : Rice avait inventé un
    système pour définir et classifier les pavages, outil sans lequel ses découvertes
    eurent été presque impossibles.</p>

    <p>L'histoire de Rice m'a fasciné et inspiré, et m'a
    rendu bêtement obsédé par les pavages. Elle nous rappelle que les mathématiques ne 
    sont pas réservées à des académiciens claquemurés dans 
    leur tour d'ivoire, mais plutôt, qu'elles peuvent offrir du plaisir et de la beauté
    aux curieuses et aux curieux.</p>

    <h3>Les permutations de Truchet, les observations de Douat</h3>

    <p>Après avoir scruté le terrain un peu, j'ai découvert les pavages de Truchet. 
    Je suis tombé sur ce bouquin écrit par Dominique Douat en 1722, <i>Méthode pour
    faire une infinité de desseins différens</i>.</p>
    <div id="narrow">
    <img src="../../images/truchet/douat-page-09.jpg"></div>

    <h3>À quoi pourraient ressembler des pavages animés ?</h3>

    <p>Je me suis dit que j'allais essayer d'animer des pavages.</p>

    <p>Première tentative d'animer, deuxième tentative. Je ne suis pas satisfait.</p>

    <p>Troisième tentative d'animer plus intéressante.</p>

    </div>
    `
};

exports.en = {
    title: "Truchet",
    date: "Winter 2017 - Ongoing",
    description: "a series of images generated by a dynamical system",
    content: String.raw `
    <div id="page"><p>
    </div>
    `
};