exports.fr = {
    title: "Truchet",
    description: "une série d'images générées par un système dynamique",
    content: String.raw `
    <div id="page"><p>

    </div>
    `
};

exports.en = {
    title: "Truchet",
    description: "a series of images generated by a dynamical system",
    content: String.raw `
    <div id="page"><p>
    </div>
    `
};