exports.fr = {
    title: "Villeray la silencieuse",
    description: "Rotations et translations répétées.",
    content: `<i>Villeray la silencieuse</i> est une série d'images générées par une variété de fonctions itératives.
    Elles ont été créées avec p5.js.`
};

exports.en = {
    title: "Silent Villeray",
    description: "Repeated rotations and translations.",
    content: `<i>Silent Villeray</i> is a series of images generated by various iterated functions. 
    They were created in JavaScript with the p5.js library.`
}

exports.link = null;
