exports.fr = {
    title: "Villeray la silencieuse",
    description: "rotations et translations répétées",
    content: `
    <div id="page">
    <p>Ces images ont été générées par rotations et translations répétées, programmées en JavaScript.</p>
    <img src="../images/villeray/villeray001.jpg">
    <img src="../images/villeray/villeray002.jpg">
    <img src="../images/villeray/villeray003.jpg">
    <img src="../images/villeray/villeray004.jpg">
    <img src="../images/villeray/villeray005.jpg">
    <img src="../images/villeray/villeray006.jpg">
    </div>
    `
};

exports.en = {
    title: "Silent Villeray",
    description: "repeated rotations and translations",
    content: `
    <div id="page">
    <p>These images were generated by repeated rotations and translations programmed in JavaScript.</p>
    <img src="../images/villeray/villeray001.jpg">
    <img src="../images/villeray/villeray002.jpg">
    <img src="../images/villeray/villeray003.jpg">
    <img src="../images/villeray/villeray004.jpg">
    <img src="../images/villeray/villeray005.jpg">
    <img src="../images/villeray/villeray006.jpg">
    </div>
    `
}

exports.link = null;
